import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto,  DM_Sans } from "next/font/google";
import "./globals.css";
import { ModalProvider} from "@/context/ModelContext";


// Load fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

const dmsans =  DM_Sans({
  subsets: ["latin"],
  variable: "--font-dancing",
  weight: ["400", "700"], // optional
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable } ${dmsans.variable} antialiased `}
      >
       <ModalProvider>{children}</ModalProvider>
      </body>
    </html>
  );
}

